# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - cinetup-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore .\CineTup.slnx

      - name: Build application
        run: dotnet build .\CineTup.slnx --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: dotnet publish
        run: dotnet publish .\CineTup.Presentation\CineTup.Presentation.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB0C379157D740B78B1759A600F7A77B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EDB9C997F0C44E9B947B31341C43870A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_13DD45A3B3504704A6AF45B9262F4845 }}

      - name: Restore dependencies
        run: dotnet restore .\CineTup.Presentation\CineTup.Presentation.csproj

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 10.*
       
      - name: Update database with EF Core migrations
        run: dotnet ef database update --project .\CineTup.Presentation\CineTup.Presentation.csproj
        env:
          ASPNETCORE_ENVIRONMENT: Production
          ConnectionStrings__DefaultConnection: ${{ secrets.DBCONNECTIONSTRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cinetup-api'
          slot-name: 'Production'
          package: .
          